[env:uno]
platform = atmelavr
board = uno
framework = arduino

upload_port = COM5
monitor_port = COM5
monitor_speed = 115200

build_src_filter =
  -<*>
  +<test1.cpp>

lib_deps =
  robtillaart/MS5611 @ ^0.5.1 
  SD
  https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary.git#v1.3.2
